apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine3.12
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: alpinetest
          image: alpine:3.12
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "sleep 3600"]