namespace: abc
namePrefix: dev-
bases:
  - ../../base

patchesStrategicMerge:
  - replica.yaml
  - image.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: myngx
    path: port.yaml


vars:
  - name: config_value
    objref:
      kind: ConfigMap
      name: myconfig
      apiVersion: v1
    fieldref:
      fieldpath: data.myconf
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: myconfig
    files:
      - myconf=mycnf.prop

