apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress-class: nginx
spec:
  rules:
    - host: test.xiaolatiao.cn
      http:
        paths:
          - path: /
            backend:
              serviceName: nginx-svc
              servicePort: 80